### ISSUE TITLE
Events (change "main" procedure)

### ISSUE THREAD

**Issue by nanalan** [haumea-lang/haumea#9]
```
to main do
    display(factorial(5))
end
```

Although `main` in C makes sense, here (since Haumea seems very english-like) it doesn't make much sense ~~- perhaps~~

```
to begin do
to start do
```

~~could work better as a starting procedure?~~

**Comment by Jonathan50** [comment]
Is there any advantage to requiring a "main" procedure at all?

**Comment by BookOwl** [comment]
It provides a natural place to put the starting code.

**Comment by nanalan** [comment]
> It provides a natural place to put the starting code.

You could put the `main` procedure _anywhere_, no?

```
to main do
  this()
end

to this do
  display(25)
end
```

If you can support it, just make Haumea a scripting language (i.e. the main function is everything not within a procedure)!

**Comment by TheMonsterFromTheDeep** [comment]
Even if main is a block, it doesn't necessarily have to be a function. What about something like
```
on entry do
    display("Hello, world!")
end
```

**Comment by BookOwl** [comment]
How about this?
```
when started do
  display(1)
end
```

**Comment by nanalan** [comment]
"when" says 'event' to me. Could we add events to the standard library (async!)

**Comment by BookOwl** [comment]
When you think about it, the program starting is basically an event. As far as other events go, sure.

**Comment by BookOwl** [comment]
Moved to https://github.com/haumea-lang/thinktank/issues/3
